destinations:
  - name: promWithNoCreds
    type: prometheus
    url: http://prometheus.monitoring.svc.cluster.local:9090

  - name: promWithBasicCreds
    type: prometheus
    url: https://prometheus-us-central1.grafana.net
    auth:
      type: basic
      username: my-username
      password: my-password
    tls:
      ca: "my ca"
      cert: "my cert"
      key: "my key"

  - name: promWithExternalSecretCreds
    type: prometheus
    url: https://prometheus-us-central1.grafana.net
    auth:
      type: basic
      usernameKey: prom-username
      passwordKey: prom-password
    secret:
      create: false
      name: my-external-secret
      namespace: some-other-namespace

  - name: promWithEmbeddedCreds
    type: prometheus
    url: http://prometheus.monitoring.svc.cluster.local:9090
    auth:
      type: basic
      username: myusername
      password: mypassword
    secret:
      embed: true
    tls:
      ca: "my ca"
      cert: "my cert"
      keyFrom: env("PROM_KEY")

  - name: promWithBearerToken
    type: prometheus
    url: http://prometheus.monitoring.svc.cluster.local:9090
    auth:
      type: bearerToken
      bearerToken: my-token

  - name: promWithEnvVarCreds
    type: prometheus
    url: https://prometheus-us-central1.grafana.net
    auth:
      type: basic
      usernameFrom: env("PROM_USERNAME")
      passwordFrom: env("PROM_PASSWORD")
    tls:
      caFrom: env("PROM_CA")
      certFrom: env("PROM_CERT")
      keyFrom: env("PROM_KEY")

  - name: loki
    type: loki
    url: http://loki.monitoring.svc.cluster.local:3100
    tenantId: 1
    auth:
      type: basic
      username: my-username
      password: my-password