destinations:
  - name: promWithNoCreds
    type: prometheus
    url: http://prometheus.monitoring.svc.cluster.local:9090

  - name: promWithBasicCreds
    type: prometheus
    url: https://prometheus-us-central1.grafana.net
    auth:
      type: basic
      username: my-username
      password: my-password

  - name: promWithExternalSecretCreds
    type: prometheus
    url: https://prometheus-us-central1.grafana.net
    auth:
      type: basic
      usernameKey: prom-username
      passwordKey: prom-password
    secret:
      create: false
      name: my-external-secret
      namespace: some-other-namespace

  - name: promWithEmbeddedCreds
    type: prometheus
    url: http://prometheus.monitoring.svc.cluster.local:9090
    auth:
      type: basic
      username: myusername
      password: mypassword
    secret:
      embed: true

  - name: promWithBearerToken
    type: prometheus
    url: http://prometheus.monitoring.svc.cluster.local:9090
    auth:
      type: bearer_token
      bearer_token: my-token

  - name: promWithEnvVarCreds
    type: prometheus
    url: https://prometheus-us-central1.grafana.net
    auth:
      type: basic
      usernameFrom: env("PROM_USERNAME")
      passwordFrom: env("PROM_PASSWORD")

  - name: loki
    type: loki
    url: http://loki.monitoring.svc.cluster.local:3100
    tenantId: 1
    auth:
      type: basic
      username: my-username
      password: my-password