{{- range $destination := $.Values.destinations }}
{{- if eq (include "destinations.secret.create_k8s_secret" $destination ) "true" }}
{{ $secrets := include (printf "destinations.%s.secrets" $destination.type) . | fromYamlArray }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "destinations.secret.k8s_secret_name" (dict "destination" $destination) | quote }}
  namespace: {{ include "destinations.secret.k8s_secret_namespace" (dict "destination" $destination "defaultNamespace" $.Release.Namespace) | quote }}
type: Opaque
data:
{{- range $secret := $secrets }}
  {{- $value := include "destinations.secret.value" (dict "destination" $destination "key" $secret) -}}
  {{- if $value }}
  {{ include "destinations.secret.key" (dict "destination" $destination "key" $secret) }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end -}}
{{- end -}}
