{{- range $name, $value := .Values.destinations }}
{{- if and (hasKey $value "secret") (hasKey $value.secret "create") ($value.secret.create) }}
  {{- if $value.secret.embed }}
    {{ fail "cannot both create and embed secret" }}
  {{- end }}
{{ if eq $value.auth.type "basic" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.secret.name | default (include "grafana-telemetry-collector.helper.k8s_name" $name) }}
type: Opaque
data:
  {{ $value.urlKey | default "url" }}: {{ $value.url | toString | b64enc | quote }}
{{- if .tenantId }}
  {{ .tenantIdKey | default "tenantId" }}: {{ .tenantId | toString | b64enc | quote }}
{{- end }}
{{- with $value.auth }}
{{- if .username }}
  {{ .usernameKey | default "username" }}: {{ .username | toString | b64enc | quote }}
{{- end }}
{{- if .password }}
  {{ .passwordKey | default "password" }}: {{ .password | toString | b64enc | quote }}
{{- end }}
{{- end }}

{{ end }}
{{ end }}
{{ end }}
